/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CoachingEnterprise;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.sql.*;

/**
 *
 * @author Deepak
 */
public class ClassDetailsAdmin extends javax.swing.JPanel {
private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/finalproject";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
     int q,i;
     String branch;
     String enterprise;
     String name,pass,test;
     byte[] image;
     String englishtest;
    /**
     * Creates new form CLassDetailsAdmin
     */
    public ClassDetailsAdmin() {
        initComponents();
    }
public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from studentclassdetailscoaching");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
   
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  
                  columnData.add(rs.getString("ID"));
                  columnData.add(rs.getString("Name"));
                  columnData.add(rs.getString("Email"));
                  columnData.add(rs.getString("TestPrep"));
                  columnData.add(rs.getString("PrepModes"));
                  columnData.add(rs.getString("Batch"));
                  columnData.add(rs.getString("EngTestPrep"));
                  columnData.add(rs.getString("EngPrepModes"));
                  columnData.add(rs.getBlob("EngBatch"));
                  columnData.add(rs.getString("Status"));
                  columnData.add(rs.getString("Test"));
                  columnData.add(rs.getString("EnglishTest"));
                }         
            
             
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }}
public void upDateDb1()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from studentclassdetailscoachingall");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
   
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  
                  columnData.add(rs.getString("ID"));
                  columnData.add(rs.getString("Name"));
      
                  columnData.add(rs.getString("Age"));
                  columnData.add(rs.getString("Gender"));
                  columnData.add(rs.getString("Email"));
                  columnData.add(rs.getString("Mobile"));
                  columnData.add(rs.getString("Branch"));
                  columnData.add(rs.getString("Enterprise"));
                  columnData.add(rs.getString("Degree"));
                   columnData.add(rs.getString("Status"));
                  columnData.add(rs.getString("Test"));
                  columnData.add(rs.getString("EnglishTest"));
                  columnData.add(rs.getString("Countries"));
                  columnData.add(rs.getString("TestPrep"));
                  columnData.add(rs.getString("PrepModes"));
                  columnData.add(rs.getString("Batch"));
                  columnData.add(rs.getString("EngTestPrep"));
                  columnData.add(rs.getString("EngPrepModes"));
                  columnData.add(rs.getString("EngBatch"));
                 
                }         
            
             
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailstbl = new javax.swing.JTable();
        viewbtn = new javax.swing.JButton();

        detailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Test Prep", "Prep Modes", "Batch", "EngTestPrep", "EngPrepModes", "EngBatch", "Status", "Test", "EnglishTest"
            }
        ));
        detailstbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailstblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detailstbl);

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(viewbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(viewbtn)
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from studentclassdetailscoachingall");
            
             rs=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)detailstbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                
                
                String id=String.valueOf(rs.getString("ID"));
                String name=String.valueOf(rs.getString("Name"));
                String email=String.valueOf(rs.getString("Email"));
                String testprep=String.valueOf(rs.getString("TestPrep"));
                String prepmodes=String.valueOf(rs.getString("PrepModes"));
                String batch=String.valueOf(rs.getString("Batch"));
                String engtestprep=String.valueOf(rs.getString("EngTestPrep"));
                String engprepmodes=String.valueOf(rs.getString("EngPrepModes"));
                String engbatch=String.valueOf(rs.getString("EngBatch"));
               
                String status =String.valueOf(rs.getString("Status"));
                 test=String.valueOf(rs.getString("Test"));
                englishtest=String.valueOf(rs.getString("EnglishTest"));
                
                String tbdata[]={id,name,email,testprep,prepmodes,batch,engtestprep,engprepmodes,engbatch,status,test,englishtest};
                
                model.addRow(tbdata);
            }
           
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewbtnActionPerformed

    private void detailstblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailstblMouseClicked
        // TODO add your handling code here:
          DefaultTableModel model=(DefaultTableModel)detailstbl.getModel();
         int SelectedRows= detailstbl.getSelectedRow();
         String nstatus="Class Completed";
   model.setValueAt(nstatus, SelectedRows, 9);
         String ntestscore=JOptionPane.showInputDialog(null, "Test Score",test);
         model.setValueAt(ntestscore, SelectedRows, 10);
          String nengtestscore=JOptionPane.showInputDialog(null, "English Proficiency Score", englishtest);
         model.setValueAt(nengtestscore, SelectedRows, 11);
               try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("update studentclassdetailscoachingall set ID=?,Name=?,Email=?,TestPrep=?,PrepModes=?, Batch=?,EngTestPrep=?,EngPrepModes=?,EngBatch=?,Status=?,Test=?,EnglishTest=? where ID=?");
         
       pst.setString(1,model.getValueAt(SelectedRows, 0).toString());
        pst.setString(2,model.getValueAt(SelectedRows, 1).toString());
        pst.setString(3,model.getValueAt(SelectedRows, 2).toString());
        pst.setString(4,model.getValueAt(SelectedRows, 3).toString());
        pst.setString(5,model.getValueAt(SelectedRows, 4).toString());
        pst.setString(6,model.getValueAt(SelectedRows, 5).toString());
        pst.setString(7,model.getValueAt(SelectedRows, 6).toString());
        pst.setString(8,model.getValueAt(SelectedRows, 7).toString());
        pst.setString(9,model.getValueAt(SelectedRows, 8).toString());
        pst.setString(10,model.getValueAt(SelectedRows, 9).toString());
        pst.setString(11,model.getValueAt(SelectedRows, 10).toString());
        pst.setString(12,model.getValueAt(SelectedRows, 11).toString());
        pst.setString(13,model.getValueAt(SelectedRows, 0).toString());
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Scores Updated Successfully");
         upDateDb();}                    
catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
         
    }
  
    }//GEN-LAST:event_detailstblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailstbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
